export type GrowthPage = {
  slug: string;
  title: string;
  eyebrow: string;
  h1: string;
  description: string;
  problem: string;
  solution: string;
  benefits: string[];
  faq: { question: string; answer: string }[];
  related: { href: string; label: string }[];
};

const serviceSeeds: Array<[string, string, string, string, string, string, string, string[]]> = [
  ["dedetizacao", "Dedetização em Franca SP", "Controle integrado", "Dedetização segura, rápida e com garantia em Franca", "Controle profissional de baratas, formigas, aranhas e outros insetos em residências e empresas de Franca e região.", "Uma aplicação genérica pode dispersar a infestação e expor pessoas, pets e alimentos sem resolver o foco.", "Inspecionamos o ambiente, identificamos a espécie e aplicamos o método adequado com orientação antes e depois do serviço.", ["Diagnóstico antes da aplicação", "Produtos profissionais registrados", "Laudo técnico e garantia descrita", "Atendimento residencial e empresarial"]],
  ["desratizacao", "Desratização em Franca", "Controle de roedores", "Desratização técnica sem improviso", "Iscas protegidas, mapeamento de pontos críticos e monitoramento para controlar ratos com segurança.", "Roedores contaminam alimentos, danificam estruturas e se reproduzem rapidamente quando abrigo e alimento continuam disponíveis.", "Mapeamos acessos, instalamos porta-iscas identificados e orientamos correções para reduzir a reincidência.", ["Porta-iscas protegidos", "Mapa de monitoramento", "Orientação preventiva", "Relatório para empresas"]],
  ["descupinizacao", "Descupinização em Franca", "Proteção patrimonial", "Cupim não avisa. A Sentinela encontra o foco.", "Tratamento contra cupim de madeira seca e cupim subterrâneo com vistoria e plano técnico.", "Quando o sinal aparece, móveis, batentes, forros e estruturas podem já estar comprometidos.", "Identificamos a espécie e o alcance da colônia para indicar tratamento localizado, barreira química ou proteção da madeira.", ["Vistoria especializada", "Método por espécie", "Proteção de móveis e estrutura", "Garantia contratual"]],
  ["controle-de-escorpioes", "Controle de Escorpiões em Franca", "Atendimento prioritário", "Viu um escorpião? Proteja sua família agora.", "Controle integrado de escorpiões em Franca com inspeção de abrigos, controle de alimento e barreiras preventivas.", "Escorpiões se escondem em frestas, entulho e redes de esgoto; somente pulverizar não elimina as condições do ambiente.", "Atuamos no foco, nas fontes de alimento e nos acessos, com recomendações práticas para manter o imóvel protegido.", ["Resposta prioritária", "Inspeção de pontos de abrigo", "Controle de baratas associado", "Plano preventivo"]],
  ["controle-de-baratas", "Controle de Baratas em Franca", "Cozinha protegida", "Baratas aparecem à noite. O foco continua ativo.", "Tratamento direcionado para baratas de esgoto e de cozinha com gel, pulverização ou combinação técnica.", "Aerossol doméstico atinge apenas os insetos visíveis e pode espalhar a colônia para outros pontos.", "A espécie e o ambiente definem o método, reduzindo exposição e atacando esconderijos e rotas de circulação.", ["Gel seletivo quando indicado", "Tratamento de frestas", "Baixo impacto na rotina", "Orientação pós-serviço"]],
  ["controle-de-formigas", "Controle de Formigas em Franca", "Tratamento direcionado", "Elimine a colônia, não apenas a trilha", "Controle profissional de formigas em cozinhas, jardins, comércios e áreas produtivas.", "Limpar a trilha remove o sinal visível, mas a rainha e a colônia permanecem ativas.", "Identificamos a rota e usamos iscas ou aplicação localizada para alcançar o foco com menor dispersão.", ["Identificação da espécie", "Iscas profissionais", "Aplicação localizada", "Prevenção de retorno"]],
  ["sanitizacao", "Sanitização de Ambientes em Franca", "Higiene ambiental", "Sanitização profissional para ambientes mais seguros", "Aplicação técnica para redução de microrganismos em ambientes residenciais e empresariais.", "Superfícies e áreas de alto contato exigem procedimento, produto e diluição adequados.", "Definimos o protocolo conforme o uso do espaço e entregamos orientação clara de liberação do ambiente.", ["Protocolo por ambiente", "Aplicação uniforme", "Registro do serviço", "Operação planejada"]],
  ["limpeza-caixa-dagua", "Limpeza de Caixa d'Água em Franca", "Água segura", "Sua caixa d'água limpa, vedada e documentada", "Higienização de reservatórios com procedimento técnico e orientação preventiva em Franca.", "Sedimentos, vedação inadequada e longos intervalos de limpeza podem comprometer a qualidade da água.", "Esvaziamos, higienizamos e orientamos a conservação do reservatório com mínima interrupção planejada.", ["Procedimento padronizado", "Proteção do reservatório", "Comprovante de execução", "Planos para condomínios"]],
];
export const services: GrowthPage[] = serviceSeeds.map(([slug,title,eyebrow,h1,description,problem,solution,benefits]) => ({slug,title,eyebrow,h1,description,problem,solution,benefits,faq:[{question:`Quanto custa ${title.toLowerCase()}?`,answer:"O valor depende da área, nível da infestação e método indicado. Envie uma foto e o bairro pelo WhatsApp para uma triagem rápida."},{question:"O serviço tem garantia?",answer:"Sim. O prazo e as condições aplicáveis são informados no orçamento e registrados no documento do serviço."}],related:[{href:"/servicos",label:"Ver todos os serviços"},{href:"/locais/dedetizacao-em-franca",label:"Atendimento em Franca"},{href:"/contato",label:"Solicitar orçamento"}]}));

const marketNames = [["residencias","Residências"],["condominios","Condomínios"],["restaurantes","Restaurantes"],["industrias","Indústrias"],["clinicas","Clínicas"],["escolas","Escolas"],["comercios","Comércios"]] as const;
export const markets: GrowthPage[] = marketNames.map(([slug,name]) => ({slug,title:`Controle de pragas para ${name} em Franca`,eyebrow:"Proteção por segmento",h1:`Saúde ambiental para ${name.toLowerCase()}, sem parar sua rotina`,description:`Plano de controle de pragas para ${name.toLowerCase()} com inspeção, cronograma e documentação em Franca e região.`,problem:"Infestações, falhas de registro e aplicações improvisadas colocam pessoas, reputação e operação em risco.",solution:"A Sentinela combina diagnóstico, execução programada, registros e orientação preventiva conforme a realidade de cada ambiente.",benefits:["Plano sob medida","Cronograma preventivo","Laudo e registro fotográfico","Atendimento prioritário"],faq:[{question:`A Sentinela atende ${name.toLowerCase()}?`,answer:`Sim. O plano é dimensionado conforme área, risco, horários e exigências do segmento de ${name.toLowerCase()}.`},{question:"É possível contratar visitas recorrentes?",answer:"Sim. Há serviço avulso e plano preventivo com frequência definida após a inspeção."}],related:[{href:"/servicos/dedetizacao",label:"Dedetização"},{href:"/servicos/desratizacao",label:"Desratização"},{href:"/contato",label:"Pedir proposta"}]}));

const cities = [["dedetizacao-em-franca","Franca","atendimento prioritário e conhecimento dos bairros"],["dedetizacao-em-ribeirao-preto","Ribeirão Preto","agenda regional sob consulta"],["dedetizacao-em-patrocinio-paulista","Patrocínio Paulista","deslocamento regional planejado"],["dedetizacao-em-cristais-paulista","Cristais Paulista","atendimento residencial e empresarial"],["dedetizacao-em-batatais","Batatais","agenda regional sob consulta"]] as const;
export const locations: GrowthPage[] = cities.map(([slug,city,detail]) => ({slug,title:`Dedetização em ${city}`,eyebrow:"Atendimento regional",h1:`Dedetização em ${city} com diagnóstico e garantia`,description:`Controle de pragas em ${city} para casas e empresas, com ${detail}.`,problem:`Cada imóvel e infestação em ${city} exige leitura do ambiente; soluções genéricas tendem a tratar apenas o sintoma.`,solution:"A triagem começa no WhatsApp. Depois, a equipe define inspeção, método, cuidados e prazo de garantia aplicável.",benefits:["Orçamento ágil pelo WhatsApp","Equipe técnica","Produtos regularizados","Comprovante de execução"],faq:[{question:`Vocês atendem toda a cidade de ${city}?`,answer:`Atendemos ${city} conforme disponibilidade de rota. Envie o bairro e a praga para confirmarmos o melhor horário.`},{question:"Como pedir orçamento?",answer:"Informe pelo WhatsApp a cidade, bairro, tipo de imóvel e, se possível, envie foto ou vídeo do sinal encontrado."}],related:[{href:"/servicos/dedetizacao",label:"Como funciona a dedetização"},{href:"/servicos/controle-de-escorpioes",label:"Controle de escorpiões"},{href:"/contato",label:"Confirmar atendimento"}]}));

export const allGrowthPages = { services, markets, locations };
