"use client";

import { useRef, useState } from "react";

/**
 * PromoVideoSection
  * Exibe o video promocional (formato YouTube/landscape) ACIMA do hero.
   * Configure NEXT_PUBLIC_PROMO_VIDEO_URL no .env com o caminho do video.
    * Ex: NEXT_PUBLIC_PROMO_VIDEO_URL=/media/sentinela/promo.mp4
     */
     export function PromoVideoSection() {
       const videoRef = useRef<HTMLVideoElement>(null);
         const [isPlaying, setIsPlaying] = useState(false);

           const videoSrc = process.env.NEXT_PUBLIC_PROMO_VIDEO_URL;

             if (!videoSrc) return null;

               const handlePlay = () => {
                   if (videoRef.current) {
                         if (isPlaying) {
                                 videoRef.current.pause();
                                         setIsPlaying(false);
                                               } else {
                                                       videoRef.current.play();
                                                               setIsPlaying(true);
                                                                     }
                                                                         }
                                                                           };

                                                                             return (
                                                                                 <section
                                                                                       id="video-promo"
                                                                                             aria-label="Video de apresentacao Sentinela Saude Ambiental"
                                                                                                   className="w-full bg-[color:var(--brand-navy)] px-4 py-10 md:py-14"
                                                                                                       >
                                                                                                             <div className="mx-auto max-w-4xl">
                                                                                                                     <p className="mb-4 text-center text-xs font-semibold uppercase tracking-widest text-[color:var(--brand-lime)]">
                                                                                                                               Conheca nosso trabalho
                                                                                                                                       </p>
                                                                                                                                               <div
                                                                                                                                                         className="group relative overflow-hidden rounded-2xl shadow-2xl"
                                                                                                                                                                   style={{ aspectRatio: "16/9" }}
                                                                                                                                                                           >
                                                                                                                                                                                     <video
                                                                                                                                                                                                 ref={videoRef}
                                                                                                                                                                                                             className="h-full w-full object-cover"
                                                                                                                                                                                                                         src={videoSrc}
                                                                                                                                                                                                                                     playsInline
                                                                                                                                                                                                                                                 preload="metadata"
                                                                                                                                                                                                                                                             onEnded={() => setIsPlaying(false)}
                                                                                                                                                                                                                                                                       />
                                                                                                                                                                                                                                                                                 {!isPlaying && (
                                                                                                                                                                                                                                                                                             <div
                                                                                                                                                                                                                                                                                                           className="absolute inset-0 flex cursor-pointer items-center justify-center bg-black/40 transition group-hover:bg-black/30"
                                                                                                                                                                                                                                                                                                                         onClick={handlePlay}
                                                                                                                                                                                                                                                                                                                                       role="button"
                                                                                                                                                                                                                                                                                                                                                     aria-label="Reproduzir video"
                                                                                                                                                                                                                                                                                                                                                                 >
                                                                                                                                                                                                                                                                                                                                                                               <span className="flex h-20 w-20 items-center justify-center rounded-full bg-[color:var(--brand-lime)] shadow-xl transition group-hover:scale-110">
                                                                                                                                                                                                                                                                                                                                                                                               <svg
                                                                                                                                                                                                                                                                                                                                                                                                                 xmlns="http://www.w3.org/2000/svg"
                                                                                                                                                                                                                                                                                                                                                                                                                                   viewBox="0 0 24 24"
                                                                                                                                                                                                                                                                                                                                                                                                                                                     fill="currentColor"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       className="ml-1 h-9 w-9 text-[color:var(--brand-navy)]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <path d="M8 5v14l11-7z" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {isPlaying && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 onClick={handlePlay}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               aria-label="Pausar video"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             className="absolute bottom-4 right-4 flex h-10 w-10 items-center justify-center rounded-full bg-black/50 text-white backdrop-blur-sm hover:bg-black/70"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <svg
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       xmlns="http://www.w3.org/2000/svg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       viewBox="0 0 24 24"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       fill="currentColor"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       className="h-5 w-5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
